#person:
#    lastName: zhangsan
#    age: 19
#    boss: false
#    borth: 2018/07/25
#    maps: {k1: v1,k2: v2}
#    list:
#      - lisi
#      - zhaoliu
#    dog:
#      name: 小狗
#      age: 12

---
server:
  port: 8081
spring:
  profiles:
    active: dev
---
---
server:
  port: 8081
spring:
  profiles: prod
---
server:
  port: 8082
spring:
  profiles: dev
---


